// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB01r6WBLoaDcfK8XjLVCfuMPD2qWuIiw8',
    appId: '1:14481600113:web:2183a04203c30c92a675d0',
    messagingSenderId: '14481600113',
    projectId: 'mynotes0001',
    authDomain: 'mynotes0001.firebaseapp.com',
    storageBucket: 'mynotes0001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqQs8OhBmMXMYuzVXIFePg9znTNFTTKA4',
    appId: '1:14481600113:android:14fc6484b27ec368a675d0',
    messagingSenderId: '14481600113',
    projectId: 'mynotes0001',
    storageBucket: 'mynotes0001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD75c5s5gKl7su3cV0VW68rBlSMGzDCWa4',
    appId: '1:14481600113:ios:04f76428ac5ef02ea675d0',
    messagingSenderId: '14481600113',
    projectId: 'mynotes0001',
    storageBucket: 'mynotes0001.appspot.com',
    iosClientId: '14481600113-qmp3quo38fqsn5a15gt4glvlqqsqd8qr.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
